version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo "Installing dependencies"
      - apt-get update -y
      - apt-get install -y awscli

  pre_build:
    commands:
      - echo "Setting the repository URI"
      - REPOSITORY_URI=861276076608.dkr.ecr.us-west-1.amazonaws.com/image-gallery
      - echo "Logging in to Amazon ECR"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION $REPOSITORY_URI

  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t myapp .
      - docker tag myapp:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR"
      - docker push $REPOSITORY_URI:latest

artifacts:
  files:
    - '**/*'