version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.23
    commands:
      - echo "Installing dependencies"
      - go mod tidy

  pre_build:
    commands:
      - echo "Running tests"
      - go test ./...

  build:
    commands:
      - echo "Building Go application"
      - go build -o myapp main.go

artifacts:
  files:
    - myapp
